diff:
	diff -iEbBwru --exclude="#runtime" --exclude="Runtime" /data/www/wechat_orders ./wechat_orders | vim -

diff_file:
	diff -iEbBwruq --exclude="#runtime" --exclude="Runtime" /data/www/wechat_orders ./wechat_orders
